version: "3"

services:
  web:
    container_name: analytics_web
    build: .
    env_file: .env
    volumes:
      - /srv/data/analytics/:/data/
    ports:
      - "${PORT}:${PORT}"
    command: >
      gunicorn analytics.asgi:application --workers 2 --max-requests 256
      --timeout 30 --bind :${PORT} --worker-class uvicorn.workers.UvicornWorker
      --error-logfile - --access-logfile -
    restart: unless-stopped
