# Generated by Django 4.0.5 on 2022-06-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='custom_cards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
