# Generated by Django 6.0.4 on 2026-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_custom_cards'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['property', 'created_at'], name='properties__propert_9b5576_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['property', 'event', 'created_at'], name='properties__propert_244021_idx'),
        ),
    ]
